"""
  Coins codes and names.
"""

COINS_NAMES = (
    ("BTC", "Bitcoin"),
    ("ETH", "Ethereum"),
    ("XRP", "Ripple"),
    ("BCH", "Bitcoin Cash"),
    ("ADA", "Cardano"),
    ("LTC", "Litecoin"),
    ("XEM", "NEM"),
    ("NEO", "NEO"),
    ("XLM", "Stellar"),
    ("MIOTA", "IOTA"),
    ("EOS", "EOS"),
    ("DASH", "Dash"),
    ("XMR", "Monero"),
    ("TRX", "TRON"),
    ("BTG", "Bitcoin Gold"),
    ("ETC", "Ethereum Classic"),
    ("QTUM", "Qtum"),
    ("ICX", "ICON"),
    ("LSK", "Lisk"),
    ("XRB", "RaiBlocks"),
    ("NANO", "Nano"),
    ("OMG", "OmiseGO"),
    ("STRAT", "Stratis"),
    ("ARDR", "Ardor"),
    ("ZEC", "Zcash"),
    ("BNB", "Binance Coin"),
    ("XVG", "Verge"),
    ("SC", "Siacoin"),
    ("PPT", "Populous"),
    ("BCN", "Bytecoin"),
    ("VEN", "VeChain"),
    ("BCC", "BitConnect"),
    ("USDT", "Tether"),
    ("SNT", "Status"),
    ("STEEM", "Steem"),
    ("BTS", "BitShares"),
    ("DOGE", "Dogecoin"),
    ("WAVES", "Waves"),
    ("KCS", "KuCoin Shares"),
    ("REP", "Augur"),
    ("ZRX", "0x"),
    ("DGB", "DigiByte"),
    ("VERI", "Veritaseum"),
    ("GNT", "Golem"),
    ("KMD", "Komodo"),
    ("GAS", "Gas"),
    ("DRGN", "Dragonchain"),
    ("QASH", "QASH"),
    ("ETN", "Electroneum"),
    ("WAX", "WAX"),
    ("DCN", "Dentacoin"),
    ("ARK", "Ark"),
    ("HSR", "Hshare"),
    ("DCR", "Decred"),
    ("SMART", "SmartCash"),
    ("BAT", "Basic Attention Token"),
    ("KNC", "Kyber Network"),
    ("PIVX", "PIVX"),
    ("LRC", "Loopring"),
    ("ZCL", "ZClassic"),
    ("SALT", "SALT"),
    ("WTC", "Walton"),
    ("GBYTE", "Byteball Bytes"),
    ("DENT", "Dent"),
    ("FUN", "FunFair"),
    ("BTM", "Bytom"),
    ("AION", "Aion"),
    ("FCT", "Factom"),
    ("XP", "Experience Points"),
    ("ETHOS", "Ethos"),
    ("GXS", "GXShares"),
    ("MAID", "MaidSafeCoin"),
    ("MONA", "MonaCoin"),
    ("AE", "Aeternity"),
    ("MED", "MediBloc"),
    ("POWR", "Power Ledger"),
    ("SYS", "Syscoin"),
    ("SUB", "Substratum"),
    ("RDD", "ReddCoin"),
    ("RHOC", "RChain"),
    ("KIN", "Kin"),
    ("NXT", "Nxt"),
    ("ENG", "Enigma"),
    ("REQ", "Request Network"),
    ("DGD", "DigixDAO"),
    ("GAME", "GameCredits"),
    ("PART", "Particl"),
    ("NXS", "Nexus"),
    ("NAS", "Nebulas"),
    ("GNO", "Gnosis"),
    ("BNT", "Bancor"),
    ("ICN", "Iconomi"),
    ("PAY", "TenX"),
    ("XDN", "DigitalNote"),
    ("ELF", "aelf"),
    ("CVC", "Civic"),
    ("XZC", "ZCoin"),
    ("EMC", "Emercoin"),
    ("BTX", "Bitcore"),
    ("LINK", "ChainLink"),
    ("BTCD", "BitcoinDark"),
    ("NEBL", "Neblio"),
    ("BTCD", "BitcoinDark"),
    ("XPA", "XPlay"),
    ("RDN", "Raiden Network Token"),
    ("PAC", "PACcoin"),
    ("CNX", "Cryptonex"),
    ("BLOCK", "Blocknet"),
    ("QSP", "Quantstamp"),
    ("SKY", "Skycoin"),
    ("VEE", "BLOCKv"),
    ("STORJ", "Storj"),
    ("PLR", "Pillar"),
    ("NAV", "NAV Coin"),
    ("RLC", "iExec RLC"),
    ("STORM", "Storm"),
    ("VTC", "Vertcoin"),
    ("MCO", "Monaco"),
    ("POE", "Po.et"),
    ("EDG", "Edgeless"),
    ("APPC", "AppCoins"),
    ("SAN", "Santiment Network Token"),
    ("BCO", "BridgeCoin"),
    ("ENJ", "Enjin Coin"),
    ("DEW", "DEW"),
    ("PPP", "PayPie"),
    ("RPX", "Red Pulse"),
    ("R", "Revain"),
    ("LEND", "ETHLend"),
    ("SNGLS", "SingularDTV"),
    ("DBC", "DeepBrain Chain"),
    ("UBQ", "Ubiq"),
    ("VIBE", "VIBE"),
    ("SRN", "SIRIN LABS Token"),
    ("ANT", "Aragon"),
    ("TNB", "Time New Bank"),
    ("PPC", "Peercoin"),
    ("BAY", "BitBay"),
    ("RCN", "Ripio Credit Network"),
    ("OST", "Simple Token"),
    ("XBY", "XTRABYTES"),
    ("ACT", "Achain"),
    ("AST", "AirSwap"),
    ("SNM", "SONM"),
    ("SPANK", "SpankChain"),
    ("EMC2", "Einsteinium"),
    ("CTR", "Centra"),
    ("QRL", "Quantum Resistant Ledger"),
    ("UKG", "Unikoin Gold"),
    ("ADX", "AdEx"),
    ("NLG", "Gulden"),
    ("WABI", "WaBi"),
    ("LBC", "LBRY Credits"),
    ("ATM", "ATMChain"),
    ("UNITY", "SuperNET"),
    ("CMT", "CyberMiles"),
    ("DATA", "Streamr DATAcoin"),
    ("ETP", "Metaverse ETP"),
    ("TRIG", "Triggers"),
    ("DTR", "Dynamic Trading Rights"),
    ("MANA", "Decentraland"),
    ("ZEN", "ZenCash"),
    ("VIA", "Viacoin"),
    ("XCP", "Counterparty"),
    ("WGR", "Wagerr"),
    ("EDO", "Eidoo"),
    ("WINGS", "Wings"),
    ("BURST", "Burst"),
    ("1ST", "FirstBlood"),
    ("CND", "Cindicator"),
    ("MOD", "Modum"),
    ("NGC", "NAGA"),
    ("DNT", "district0x"),
    ("PRL", "Oyster"),
    ("MLN", "Melon"),
    ("AGRS", "Agoras Tokens"),
    ("THC", "HempCoin"),
    ("NULS", "Nuls"),
    ("UTK", "UTRUST"),
    ("FUEL", "Etherparty"),
    ("MGO", "MobileGo"),
    ("ITC", "IoT Chain"),
    ("MTL", "Metal"),
    ("RISE", "Rise"),
    ("AMB", "Ambrosus"),
    ("VOX", "Voxels"),
    ("TAU", "Lamden"),
    ("BRD", "Bread"),
    ("IOC", "I/O Coin"),
    ("HVN", "Hive"),
    ("CFI", "Cofound.it"),
    ("CLOAK", "CloakCoin"),
    ("XAS", "Asch"),
    ("CDT", "CoinDash"),
    ("COSS", "COSS"),
    ("TRST", "WeTrust"),
    ("DCT", "DECENT"),
    ("TNT", "Tierion"),
    ("GTO", "Gifto"),
    ("AEON", "Aeon"),
    ("MNX", "MinexCoin"),
    ("IXT", "iXledger"),
    ("VOISE", "Voise"),
    ("NMC", "Namecoin"),
    ("SHIFT", "Shift"),
    ("HST", "Decision Token"),
    ("GRS", "Groestlcoin"),
    ("FTC", "Feathercoin"),
    ("SLS", "SaluS"),
    ("LUN", "Lunyr"),
    ("PRS", "Presearch"),
    ("JINN", "Jinn"),
    ("INK", "Ink"),
    ("GVT", "Genesis Vision"),
    ("PURA", "Pura"),
    ("XSPEC", "Spectrecoin"),
    ("TKN", "TokenCard"),
    ("TAAS", "TaaS"),
    ("SAFEX", "Safe Exchange Coin"),
    ("VIB", "Viberate"),
    ("MTH", "Monetha"),
    ("DLT", "Agrello"),
    ("GRID", "Grid+"),
    ("GUP", "Matchpool"),
    ("LKK", "Lykke"),
    ("MOON", "Mooncoin"),
    ("XSH", "SHIELD"),
    ("ADT", "adToken"),
    ("YOYOW", "YOYOW"),
    ("EVX", "Everex"),
    ("HMQ", "Humaniq"),
    ("DPY", "Delphy"),
    ("ECC", "ECC"),
    ("DRT", "DomRaider"),
    ("DAT", "Datum"),
    ("LA", "LAToken"),
    ("AMP", "Synereo"),
    ("SLR", "SolarCoin"),
    ("WRC", "Worldcore"),
    ("CRW", "Crown"),
    ("POT", "PotCoin"),
    ("PASC", "Pascal Coin"),
    ("PEPECASH", "Pepe Cash"),
    ("DMD", "Diamond"),
    ("XEL", "Elastic"),
    ("PAYX", "Paypex"),
    ("MER", "Mercury"),
    ("FLASH", "Flash"),
    ("XWC", "WhiteCoin"),
    ("DOVU", "Dovu"),
    ("ZSC", "Zeusshield"),
    ("SIB", "SIBCoin"),
    ("MSP", "Mothership"),
    ("BOT", "Bodhi"),
    ("BITCNY", "bitCNY"),
    ("BLK", "BlackCoin"),
    ("ONION", "DeepOnion"),
    ("NET", "Nimiq"),
    ("TIX", "Blocktix"),
    ("DIME", "Dimecoin"),
    ("FAIR", "FairCoin"),
    ("ION", "ION"),
    ("DBIX", "DubaiCoin"),
    ("DNA", "EncrypGen"),
    ("NLC2", "NoLimitCoin"),
    ("EXP", "Expanse"),
    ("GRC", "GridCoin"),
    ("SNOV", "Snovio"),
    ("MDA", "Moeda Loyalty Points"),
    ("VRC", "VeriCoin"),
    ("NSR", "NuShares"),
    ("NYC", "NewYorkCoin"),
    ("PHR", "Phore"),
    ("GOLOS", "Golos"),
    ("ORME", "Ormeus Coin"),
    ("NMR", "Numeraire"),
    ("DIVX", "Divi"),
    ("SNC", "SunContract"),
    ("AIR", "AirToken"),
    ("LIFE", "LIFE"),
    ("NEU", "Neumark"),
    ("POLL", "ClearPoll"),
    ("PND", "Pandacoin"),
    ("XMY", "Myriad"),
    ("PRO", "Propy"),
    ("PPY", "Peerplays"),
    ("BITB", "Bean Cash"),
    ("NEOS", "NeosCoin"),
    ("RBY", "Rubycoin"),
    ("AC", "AsiaCoin"),
    ("ART", "Maecenas"),
    ("STX", "Stox"),
    ("OK", "OKCash"),
    ("NXC", "Nexium"),
    ("RVT", "Rivetz"),
    ("IFT", "InvestFeed"),
    ("RADS", "Radium"),
    ("DTB", "Databits"),
    ("BCPT", "BlockMason Credit Protocol"),
    ("MUE", "MonetaryUnit"),
    ("BNTY", "Bounty0x"),
    ("XRL", "Rialto"),
    ("OTN", "Open Trading Network"),
    ("OMNI", "Omni"),
    ("ATB", "ATBCoin"),
    ("CAG", "Change"),
    ("PTOY", "Patientory"),
    ("KICK", "KickCoin"),
    ("BLUE", "BLUE"),
    ("XNN", "Xenon"),
    ("FLO", "FlorinCoin"),
    ("BIS", "Bismuth"),
    ("HDG", "Hedge"),
    ("CRED", "Verify"),
    ("BCAP", "BCAP"),
    ("ALIS", "ALIS"),
    ("PRG", "Paragon"),
    ("SBD", "Steem Dollars"),
    ("TIPS", "FedoraCoin"),
    ("PKT", "Playkey"),
    ("DBET", "DecentBet"),
    ("OAX", "OAX"),
    ("ALQO", "ALQO"),
    ("ARN", "Aeron"),
    ("ELIX", "Elixir"),
    ("CREDO", "Credo"),
    ("BMC", "Blackmoon Crypto"),
    ("MYB", "MyBit Token"),
    ("SWT", "Swarm City"),
    ("ENRG", "Energycoin"),
    ("POSW", "PoSW Coin"),
    ("INCNT", "Incent"),
    ("BCY", "Bitcrystals"),
    ("LMC", "LoMoCoin"),
    ("KLC", "KiloCoin"),
    ("TGT", "Target Coin"),
    ("ODN", "Obsidian"),
    ("COLX", "ColossusCoinXT"),
    ("CLAM", "Clams"),
    ("LINDA", "Linda"),
    ("FLDC", "FoldingCoin"),
    ("GCR", "Global Currency Reserve"),
    ("CAT", "BlockCAT"),
    ("ICOS", "ICOS"),
    ("MINT", "Mintcoin"),
    ("LOC", "LockChain"),
    ("ABY", "ArtByte"),
    ("COVAL", "Circuits of Value"),
    ("GBX", "GoByte"),
    ("SOAR", "Soarcoin"),
    ("XAUR", "Xaurum"),
    ("LUX", "LUXCoin"),
    ("GAM", "Gambit"),
    ("MUSIC", "Musicoin"),
    ("HEAT", "HEAT"),
    ("WCT", "Waves Community Token"),
    ("OXY", "Oxycoin"),
    ("BQ", "bitqy"),
    ("NTRN", "Neutron"),
    ("IOP", "Internet of People"),
    ("PIRL", "Pirl"),
    ("MYST", "Mysterium"),
    ("ECN", "E-coin"),
    ("ONG", "onG.social"),
    ("PFR", "Payfair"),
    ("LEO", "LEOcoin"),
    ("ATL", "ATLANT"),
    ("PBL", "Publica"),
    ("XST", "Stealthcoin"),
    ("PST", "Primas"),
    ("BSD", "BitSend"),
    ("OCT", "OracleChain"),
    ("BET", "DAO.Casino"),
    ("BWK", "Bulwark"),
    ("GMT", "Mercury Protocol"),
    ("AVT", "Aventus"),
    ("XMCC", "Monoeci"),
    ("TIME", "Chronobank"),
    ("FLIXX", "Flixxo"),
    ("SEQ", "Sequence"),
    ("ADC", "AudioCoin"),
    ("XLR", "Solaris"),
    ("QAU", "Quantum"),
    ("PLBT", "Polybius"),
    ("QUN", "QunQun"),
    ("ZOI", "Zoin"),
    ("BITUSD", "bitUSD"),
    ("CVCOIN", "CVCoin"),
    ("ESP", "Espers"),
    ("OBITS", "OBITS"),
    ("BBR", "Boolberry"),
    ("UNO", "Unobtanium"),
    ("ATMS", "Atmos"),
    ("SEND", "Social Send"),
    ("UFR", "Upfiring"),
    ("XPM", "Primecoin"),
    ("XVC", "Vcash"),
    ("PINK", "PinkCoin"),
    ("CSNO", "BitDice"),
    ("SPF", "SportyFi"),
    ("BDL", "Bitdeal"),
    ("RMC", "Russian Miner Coin"),
    ("GEO", "GeoCoin"),
    ("NIO", "Autonio"),
    ("FRST", "FirstCoin"),
    ("HUSH", "Hush"),
    ("EAC", "EarthCoin"),
    ("ADST", "AdShares"),
    ("WISH", "MyWish"),
    ("SUMO", "Sumokoin"),
    ("SPHR", "Sphere"),
    ("MAG", "Magnet"),
    ("BTM", "Bitmark"),
    ("SPRTS", "Sprouts"),
    ("DICE", "Etheroll"),
    ("PIX", "Lampix"),
    ("PLU", "Pluton"),
    ("PRO", "ProChain"),
    ("PTC", "Pesetacoin"),
    ("ECOB", "Ecobit"),
    ("CURE", "Curecoin"),
    ("HGT", "HelloGold"),
    ("VSX", "Vsync"),
    ("SPR", "SpreadCoin"),
    ("OPT", "Opus"),
    ("NVST", "NVO"),
    ("CRB", "Creditbit"),
    ("XUC", "Exchange Union"),
    ("RC", "RussiaCoin"),
    ("RIC", "Riecoin"),
    ("QWARK", "Qwark"),
    ("INN", "Innova"),
    ("REX", "REX"),
    ("TZC", "TrezarCoin"),
    ("ZNY", "Bitzeny"),
    ("HKN", "Hacken"),
    ("TX", "TransferCoin"),
    ("PLAY", "HEROcoin"),
    ("DOPE", "DopeCoin"),
    ("FYP", "FlypMe"),
    ("UFO", "UFO Coin"),
    ("BELA", "Bela"),
    ("UNIT", "Universal Currency"),
    ("BON", "Bonpay"),
    ("CRAVE", "Crave"),
    ("B2B", "B2B"),
    ("CANN", "CannabisCoin"),
    ("BPL", "Blockpool"),
    ("WILD", "Wild Crypto"),
    ("XTO", "Tao"),
    ("MEME", "Memetic / PepeCoin"),
    ("XBC", "Bitcoin Plus"),
    ("ITNS", "IntenseCoin"),
    ("NVC", "Novacoin"),
    ("ZER", "Zero"),
    ("SYNX", "Syndicate"),
    ("TCC", "The ChampCoin"),
    ("VRM", "VeriumReserve"),
    ("BLITZ", "Blitzcash"),
    ("BRK", "Breakout"),
    ("ASTRO", "Astro"),
    ("SNRG", "Synergy"),
    ("CARBON", "Carboncoin"),
    ("KORE", "Kore"),
    ("HYP", "HyperStake"),
    ("IND", "Indorse Token"),
    ("AUR", "Auroracoin"),
    ("RKC", "Royal Kingdom Coin"),
    ("HBT", "Hubii Network"),
    ("GLD", "GoldCoin"),
    ("NOTE", "DNotes"),
    ("REAL", "REAL"),
    ("BTDX", "Bitcloud"),
    ("START", "Startcoin"),
    ("MTNC", "Masternodecoin"),
    ("RUP", "Rupee"),
    ("VSL", "vSlice"),
    ("DRP", "DCORP"),
    ("CREA", "Creativecoin"),
    ("CRC", "CrowdCoin"),
    ("PRIX", "Privatix"),
    ("CHC", "ChainCoin"),
    ("BRX", "Breakout Stake"),
    ("DOT", "Dotcoin"),
    ("PGL", "Prospectors Gold"),
    ("BUZZ", "BuzzCoin"),
    ("BTCZ", "BitcoinZ"),
    ("EDR", "E-Dinar Coin"),
    ("AHT", "Bowhead"),
    ("INXT", "Internxt"),
    ("USNBT", "NuBits"),
    ("TFL", "TrueFlip"),
    ("VIVO", "VIVO"),
    ("EXCL", "ExclusiveCoin"),
    ("HWC", "HollyWoodCoin"),
    ("SCL", "Social"),
    ("2GIVE", "2GIVE"),
    ("TOA", "ToaCoin"),
    ("1337", "1337"),
    ("SSS", "Sharechain"),
    ("ADL", "Adelphoi"),
    ("PURE", "Pure"),
    ("VTR", "vTorrent"),
    ("XGOX", "XGOX"),
    ("EBST", "eBoost"),
    ("PDC", "Project Decorum"),
    ("ELLA", "Ellaism"),
    ("DGPT", "DigiPulse"),
    ("TKS", "Tokes"),
    ("ETT", "EncryptoTel [WAVES]"),
    ("PZM", "PRIZM"),
    ("TRUST", "TrustPlus"),
    ("IXC", "Ixcoin"),
    ("ERC", "EuropeCoin"),
    ("MBRS", "Embers"),
    ("PROC", "ProCurrency"),
    ("EBTC", "eBitcoin"),
    ("EQT", "EquiTrader"),
    ("ERO", "Eroscoin"),
    ("BASH", "LuckChain"),
    ("FRD", "Farad"),
    ("FOR", "FORCE"),
    ("SXC", "Sexcoin"),
    ("ALT", "Altcoin"),
    ("XMG", "Magi"),
    ("DYN", "Dynamic"),
    ("XFT", "Footy Cash"),
    ("BBT", "BitBoost"),
    ("ZEPH", "Zephyr"),
    ("HUC", "HunterCoin"),
    ("DAI", "Dai"),
    ("MKR", "Maker"),
    ("CDX", "Commodity Ad Network"),
    ("WAND", "WandX"),
    ("NOBL", "NobleCoin"),
    ("VIDZ", "PureVidz"),
    ("EGC", "EverGreenCoin"),
    ("TRC", "Terracoin"),
    ("ANC", "Anoncoin"),
    ("WDC", "WorldCoin"),
    ("QRK", "Quark"),
    ("PUT", "PutinCoin"),
    ("REC", "Regalcoin"),
    ("ZRC", "ZrCoin"),
    ("KRB", "Karbo"),
    ("PKB", "ParkByte"),
    ("APX", "APX"),
    ("STU", "bitJob"),
    ("LINX", "Linx"),
    ("SMART", "SmartBillions"),
    ("QVT", "Qvolta"),
    ("HAL", "Halcyon"),
    ("FLIK", "FLiK"),
    ("GOOD", "Goodomy"),
    ("NDC", "NEVERDIE"),
    ("CTX", "CarTaxi Token"),
    ("MXT", "MarteXcoin"),
    ("GIM", "Gimli"),
    ("PING", "CryptoPing"),
    ("CHIPS", "CHIPS"),
    ("ELTCOIN", "ELTCOIN"),
    ("BTCS", "Bitcoin Scrypt"),
    ("EFYT", "Ergo"),
    ("MEC", "Megacoin"),
    ("BLU", "BlueCoin"),
    ("HOLD", "Interstellar Holdings"),
    ("STAK", "STRAKS"),
    ("DNR", "Denarius"),
    ("MCAP", "MCAP"),
    ("EFL", "e-Gulden"),
    ("UNIFY", "Unify"),
    ("CMPCO", "CampusCoin"),
    ("CBX", "Crypto Bullion"),
    ("ABJ", "Abjcoin"),
    ("HAT", "Hawala.Today"),
    ("RNS", "Renos"),
    ("RAIN", "Condensate"),
    ("ARC", "ArcticCoin"),
    ("DCY", "Dinastycoin"),
    ("DP", "DigitalPrice"),
    ("YOC", "Yocoin"),
    ("ECASH", "Ethereum Cash"),
    ("POP", "PopularCoin"),
    ("FLT", "FlutterCoin"),
    ("PBT", "Primalbase Token"),
    ("XLC", "LeviarCoin"),
    ("INSN", "InsaneCoin"),
    ("MONK", "Monkey Project"),
    ("CNT", "Centurion"),
    ("DAR", "Darcrus"),
    ("EPY", "Emphy"),
    ("GCC", "TheGCCcoin"),
    ("ETG", "Ethereum Gold"),
    ("ERC20", "ERC20"),
    ("ETBS", "Ethbits"),
    ("MOIN", "Moin"),
    ("CDN", "Canada eCoin"),
    ("ITT", "Intelligent Trading Tech"),
    ("STA", "Starta"),
    ("ZEIT", "Zeitcoin"),
    ("XCN", "Cryptonite"),
    ("ECA", "Electra"),
    ("XCPO", "Copico"),
    ("ADZ", "Adzcoin"),
    ("BRO", "Bitradio"),
    ("FJC", "FujiCoin"),
    ("BTA", "Bata"),
    ("LGD", "Legends Room"),
    ("GRE", "Greencoin"),
    ("NET", "NetCoin"),
    ("V", "Version"),
    ("CRM", "Cream"),
    ("JET", "Jetcoin"),
    ("ELE", "Elementrem"),
    ("UNB", "UnbreakableCoin"),
    ("NKA", "IncaKoin"),
    ("UIS", "Unitus"),
    ("SIFT", "Smart Investment Fund Token"),
    ("SCORE", "Scorecoin"),
    ("LDOGE", "LiteDoge"),
    ("IFLT", "InflationCoin"),
    ("INFX", "Influxcoin"),
    ("OCL", "Oceanlab"),
    ("CFT", "CryptoForecast"),
    ("MCRN", "MACRON"),
    ("BYC", "Bytecent"),
    ("STN", "Steneum Coin"),
    ("KLN", "Kolion"),
    ("MZC", "MazaCoin"),
    ("TES", "TeslaCoin"),
    ("MAC", "Machinecoin"),
    ("FYN", "FundYourselfNow"),
    ("AU", "AurumCoin"),
    ("LNK", "Link Platform"),
    ("ALTCOM", "AltCommunity Coin"),
    ("KEK", "KekCoin"),
    ("FUCK", "FuckToken"),
    ("DFT", "DraftCoin"),
    ("STRC", "StarCredits"),
    ("ORB", "Orbitcoin"),
    ("SAGA", "SagaCoin"),
    ("CPC", "Capricoin"),
    ("MRT", "Miners' Reward Token"),
    ("CCRB", "CryptoCarbon"),
    ("EL", "Elcoin"),
    ("DGC", "Digitalcoin"),
    ("DSR", "Desire"),
    ("TROLL", "Trollcoin"),
    ("FST", "Fastcoin"),
    ("PIPL", "PiplCoin"),
    ("XPD", "PetroDollar"),
    ("ACC", "Accelerator Network"),
    ("TRCT", "Tracto"),
    ("EBET", "EthBet"),
    ("HTC", "HitCoin"),
    ("XCXT", "CoinonatX"),
    ("MBI", "Monster Byte"),
    ("I0C", "I0Coin"),
    ("MNE", "Minereum"),
    ("MOJO", "MojoCoin"),
    ("FC2", "FuelCoin"),
    ("SMC", "SmartCoin"),
    ("TKR", "CryptoInsight"),
    ("ATOM", "Atomic Coin"),
    ("GRWI", "Growers International"),
    ("ZENI", "Zennies"),
    ("RIYA", "Etheriya"),
    ("BIGUP", "BigUp"),
    ("EMV", "Ethereum Movie Venture"),
    ("KURT", "Kurrent"),
    ("ZET", "Zetacoin"),
    ("FCN", "Fantomcoin"),
    ("BBP", "BiblePay"),
    ("ENT", "Eternity"),
    ("VISIO", "Visio"),
    ("Q2C", "QubitCoin"),
    ("NUKO", "Nekonium"),
    ("NETKO", "Netko"),
    ("ITI", "iTicoin"),
    ("DEM", "Deutsche eMark"),
    ("DAXX", "DaxxCoin"),
    ("IETH", "iEthereum"),
    ("ATS", "Authorship"),
    ("SKIN", "SkinCoin"),
    ("ROC", "Rasputin Online Coin"),
    ("DFS", "DFSCoin"),
    ("HPC", "Happycoin"),
    ("POS", "PoSToken"),
    ("UTC", "UltraCoin"),
    ("BTCRED", "Bitcoin Red"),
    ("SDC", "ShadowCash"),
    ("BPC", "Bitpark Coin"),
    ("TRI", "Triangles"),
    ("42", "42-coin"),
    ("SMLY", "SmileyCoin"),
    ("BTCR", "Bitcurrency"),
    ("BTB", "BitBar"),
    ("GAIA", "GAIA"),
    ("CFD", "Confido"),
    ("HODL", "HOdlcoin"),
    ("PIGGY", "Piggycoin"),
    ("KOBO", "Kobocoin"),
    ("TTC", "TittieCoin"),
    ("ACC", "AdCoin"),
    ("XBL", "Billionaire Token"),
    ("BITS", "Bitstar"),
    ("CCO", "Ccore"),
    ("TRUMP", "TrumpCoin"),
    ("ARI", "Aricoin"),
    ("MAX", "MaxCoin"),
    ("RBT", "Rimbit"),
    ("DLC", "Dollarcoin"),
    ("CCT", "Crystal Clear"),
    ("STARS", "StarCash Network"),
    ("GUN", "Guncoin"),
    ("HBN", "HoboNickels"),
    ("OPAL", "Opal"),
    ("ZCG", "Zlancer"),
    ("LANA", "LanaCoin"),
    ("TIT", "Titcoin"),
    ("AMS", "AmsterdamCoin"),
    ("NYAN", "Nyancoin"),
    ("WGO", "WavesGo"),
    ("SUPER", "SuperCoin"),
    ("OTX", "Octanox"),
    ("POST", "PostCoin"),
    ("AMMO", "Ammo Reloaded"),
    ("DSH", "Dashcoin"),
    ("SGR", "Sugar Exchange"),
    ("DRXNE", "DROXNE"),
    ("TRK", "Truckcoin"),
    ("C2", "Coin2.1"),
    ("XJO", "Joulecoin"),
    ("PASL", "Pascal Lite"),
    ("GB", "GoldBlocks"),
    ("FUNC", "FUNCoin"),
    ("DIX", "Dix Asset"),
    ("BLAS", "BlakeStar"),
    ("ETHD", "Ethereum Dark"),
    ("IMS", "Independent Money System"),
    ("VLT", "Veltor"),
    ("BCF", "Bitcoin Fast"),
    ("CJ", "Cryptojacks"),
    ("WHL", "WhaleCoin"),
    ("ARG", "Argentum"),
    ("SIGT", "Signatum"),
    ("RED", "RedCoin"),
    ("BRIT", "BritCoin"),
    ("WTT", "Giga Watt Token"),
    ("BUCKS", "SwagBucks"),
    ("PAK", "Pakcoin"),
    ("8BIT", "8Bit"),
    ("XIOS", "Xios"),
    ("BLOCKPAY", "BlockPay"),
    ("XPTX", "PlatinumBAR"),
    ("XHI", "HiCoin"),
    ("AIB", "Advanced Internet Blocks"),
    ("CRX", "Chronos"),
    ("CUBE", "DigiCube"),
    ("XGR", "GoldReserve"),
    ("GRIM", "Grimcoin"),
    ("FNC", "FinCoin"),
    ("UNY", "Unity Ingot"),
    ("PXC", "Phoenixcoin"),
    ("ONX", "Onix"),
    ("XPY", "PayCoin"),
    ("MNM", "Mineum"),
    ("PR", "Prototanium"),
    ("888", "OctoCoin"),
    ("UNIC", "UniCoin"),
    ("EVIL", "Evil Coin"),
    ("XCT", "C-Bit"),
    ("MNC", "Mincoin"),
    ("PCOIN", "Pioneer Coin"),
    ("KUSH", "KushCoin"),
    ("CON", "PayCon"),
    ("808", "808Coin"),
    ("CHESS", "ChessCoin"),
    ("CACH", "CacheCoin"),
    ("TGC", "Tigercoin"),
    ("KED", "Darsek"),
    ("CNO", "Coin(O)"),
    ("XRA", "Ratecoin"),
    ("EGAS", "ETHGAS"),
    ("LCP", "Litecoin Plus"),
    ("SLG", "Sterlingcoin"),
    ("LTB", "LiteBar"),
    ("SRC", "SecureCoin"),
    ("CHAN", "ChanCoin"),
    ("HNC", "Helleniccoin"),
    ("CCN", "CannaCoin"),
    ("BTWTY", "Bit20"),
    ("ICN", "iCoin"),
    ("DDF", "DigitalDevelopersFund"),
    ("DUO", "ParallelCoin"),
    ("EOT", "EOT Token"),
    ("YTN", "YENTEN"),
    ("COAL", "BitCoal"),
    ("GAP", "Gapcoin"),
    ("XRE", "RevolverCoin"),
    ("NTO", "Fujinto"),
    ("BERN", "BERNcash"),
    ("NTWK", "Network Token"),
    ("TSE", "Tattoocoin (Standard Edition)"),
    ("PXI", "Prime-XI"),
    ("LBTC", "LiteBitcoin"),
    ("MARS", "Marscoin"),
    ("QTL", "Quatloo"),
    ("CNNC", "Cannation"),
    ("RLT", "RouletteToken"),
    ("SPACE", "SpaceCoin"),
    ("DALC", "Dalecoin"),
    ("EUC", "Eurocoin"),
    ("HERO", "Sovereign Hero"),
    ("BLC", "Blakecoin"),
    ("VAL", "Valorbit"),
    ("TRDT", "Trident Group"),
    ("KRONE", "Kronecoin"),
    ("BITBTC", "bitBTC"),
    ("SDRN", "Senderon"),
    ("EMD", "Emerald Crypto"),
    ("SWING", "Swing"),
    ("MST", "MustangCoin"),
    ("BAS", "BitAsean"),
    ("ZZC", "ZoZoCoin"),
    ("RBIES", "Rubies"),
    ("ZUR", "Zurcoin"),
    ("HXX", "Hexx"),
    ("MAR", "Marijuanacoin"),
    ("BTPL", "Bitcoin Planet"),
    ("JIN", "Jin Coin"),
    ("KAYI", "Kayicoin"),
    ("BOLI", "Bolivarcoin"),
    ("UNITS", "GameUnits"),
    ("BRAT", "BROTHER"),
    ("BXT", "BitTokens"),
    ("BTQ", "BitQuark"),
    ("CYP", "Cypher"),
    ("EBCH", "eBitcoinCash"),
    ("HONEY", "Honey"),
    ("TAG", "TagCoin"),
    ("BSTY", "GlobalBoost-Y"),
    ("PHS", "Philosopher Stones"),
    ("VUC", "Virta Unique Coin"),
    ("VOT", "VoteCoin"),
    ("SOON", "SoonCoin"),
    ("ARCO", "AquariusCoin"),
    ("EVO", "Evotion"),
    ("REE", "ReeCoin"),
    ("GP", "GoldPieces"),
    ("611", "SixEleven"),
    ("MOTO", "Motocoin"),
    ("CAT", "Catcoin"),
    ("MAO", "Mao Zedong"),
    ("$$$", "Money"),
    ("ICE", "iDice"),
    ("STV", "Sativacoin"),
    ("XVP", "Virtacoinplus"),
    ("MAD", "SatoshiMadness"),
    ("QCN", "QuazarCoin"),
    ("BUMBA", "BumbaCoin"),
    ("TALK", "BTCtalkcoin"),
    ("NRO", "Neuro"),
    ("ALL", "Allion"),
    ("CASH", "Cashcoin"),
    ("GPL", "Gold Pressed Latinum"),
    ("ICOB", "ICOBID"),
    ("GLT", "GlobalToken"),
    ("SOIL", "SOILcoin"),
    ("MTLMC3", "Metal Music Coin"),
    ("XCO", "X-Coin"),
    ("EAGLE", "EagleCoin"),
    ("XBTS", "Beatcoin"),
    ("BITZ", "Bitz"),
    ("GPU", "GPU Coin"),
    ("RPC", "RonPaulCoin"),
    ("ACOIN", "Acoin"),
    ("BITSILVER", "bitSilver"),
    ("XCRE", "Creatio"),
    ("MAY", "Theresa May Coin"),
    ("FUZZ", "FuzzBalls"),
    ("SFC", "Solarflarecoin"),
    ("ERY", "Eryllium"),
    ("CPN", "CompuCoin"),
    ("LTCU", "LiteCoin Ultra"),
    ("EREAL", "eREAL"),
    ("NEVA", "NevaCoin"),
    ("TEK", "TEKcoin"),
    ("NEWB", "Newbium"),
    ("HMP", "HempCoin"),
    ("BIP", "BipCoin"),
    ("SONG", "SongCoin"),
    ("AERM", "Aerium"),
    ("EXN", "ExchangeN"),
    ("DRS", "Digital Rupees"),
    ("CXT", "Coinonat"),
    ("BLN", "Bolenum"),
    ("BENJI", "BenjiRolls"),
    ("ECO", "EcoCoin"),
    ("FLAX", "Flaxscript"),
    ("SLEVIN", "Slevin"),
    ("CMT", "Comet"),
    ("SPT", "Spots"),
    ("LEA", "LeaCoin"),
    ("USDE", "USDe"),
    ("300", "300 Token"),
    ("IMX", "Impact"),
    ("BITGOLD", "bitGold"),
    ("WORM", "HealthyWormCoin"),
    ("MSCN", "Master Swiscoin"),
    ("GTC", "Global Tour Coin"),
    ("TAJ", "TajCoin"),
    ("BNX", "BnrtxCoin"),
    ("BOAT", "BOAT"),
    ("LUNA", "Luna Coin"),
    ("OFF", "Cthulhu Offerings"),
    ("UET", "Useless Ethereum Token"),
    ("ASAFE2", "AllSafe"),
    ("TOKEN", "SwapToken"),
    ("VEC2", "VectorAI"),
    ("RUPX", "Rupaya"),
    ("ANTI", "AntiBitcoin"),
    ("DBTC", "Debitcoin"),
    ("TOR", "Torcoin"),
    ("VPRC", "VapersCoin"),
    ("KNC", "KingN Coin"),
    ("DLISK", "DAPPSTER"),
    ("WOMEN", "WomenCoin"),
    ("XBTC21", "Bitcoin 21"),
    ("ICON", "Iconic"),
    ("ATX", "Artex Coin"),
    ("ROOFS", "Roofs"),
    ("SKC", "Skeincoin"),
    ("PLACO", "PlayerCoin"),
    ("ZMC", "ZetaMicron"),
    ("XCS", "CybCSec"),
    ("PRX", "Printerium"),
    ("QBC", "Quebecoin"),
    ("URO", "Uro"),
    ("MILO", "MiloCoin"),
    ("BITEUR", "bitEUR"),
    ("PLNC", "PLNcoin"),
    ("WBB", "Wild Beast Block"),
    ("G3N", "G3N"),
    ("VOLT", "Bitvolt"),
    ("GEERT", "GeertCoin"),
    ("PONZI", "PonziCoin"),
    ("PRC", "PRCoin"),
    ("DIBC", "DIBCOIN"),
    ("LTCR", "Litecred"),
    ("ORLY", "Orlycoin"),
    ("SOCC", "SocialCoin"),
    ("HVCO", "High Voltage"),
    ("CAB", "Cabbage"),
    ("VLTC", "Vault Coin"),
    ("BRAIN", "Braincoin"),
    ("ACP", "AnarchistsPrime"),
    ("IBANK", "iBank"),
    ("PEX", "PosEx"),
    ("CRDNC", "Credence Coin"),
    ("DOLLAR", "Dollar Online"),
    ("URC", "Unrealcoin"),
    ("CTIC3", "Coimatic 3.0"),
    ("VRS", "Veros"),
    ("SCS", "Speedcash"),
    ("BIOB", "BioBar"),
    ("ARGUS", "Argus"),
    ("JOBS", "JobsCoin"),
    ("IMPS", "ImpulseCoin"),
    ("NANOX", "Project-X"),
    ("CTIC2", "Coimatic 2.0"),
    ("ELS", "Elysium"),
    ("P7C", "P7Coin"),
    ("LVPS", "LevoPlus"),
    ("EGO", "EGO"),
    ("CREVA", "CrevaCoin"),
    ("ULA", "Ulatech"),
    ("CONX", "Concoin"),
    ("FXE", "FuturXe"),
    ("MGM", "Magnum"),
    ("XRC", "Rawcoin"),
    ("GSR", "GeyserCoin"),
    ("TSTR", "Tristar Coin"),
    ("XNG", "Enigma"),
    ("SLFI", "Selfiecoin"),
    ("HMC", "HarmonyCoin"),
    ("DGCS", "Digital Credits"),
    ("EBT", "Ebittree Coin"),
    ("DMB", "Digital Money Bits"),
    ("ABN", "Abncoin"),
    ("CALC", "CaliphCoin"),
    ("APW", "AppleCoin"),
    ("PHO", "Photon"),
    ("GCN", "GCoin"),
    ("VTA", "Virtacoin"),
    ("SWIFT", "Bitswift"),
    ("FUNK", "The Cypherfunks"),
    ("RUSTBITS", "Rustbits"),
    ("ICOO", "ICO OpenLedger"),
    ("BUN", "BunnyCoin"),
    ("JNS", "Janus"),
    ("XTZ", "Tezos"),
    ("POLY", "Polymath"),
    ("GRT", "The Graph"),
    ("ARRR", "Pirate Chain"),
    ("WOW", "Wownero"),
    ("SUTER", "Suter Token"),

# 2021-04-22 additions
    ("RVN",     "Ravencoin"),
    ("UBQ",     "Ubiq"),
    ("AVAX",    "Avalanche"),
    ("HIVE",    "Hive"),
    ("HBD",     "Hive Dollar"),

    ("BAN",     "Banano"),
    ("CFG",     "Centrifuge"),
)
    # ("BTG", "Bitgem"),

COIN_NAMES_DICT = dict(COINS_NAMES)

def coin_name(symbol):
    """
    Return full name of the coin ``symbol``
    """

    return COIN_NAMES_DICT.get(symbol, "")
